apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world-pod
  name: hello-world-pod
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: hello-world-pod
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}