apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebindread
  namespace: cau3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-readonly
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: k8s-readonly