apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume01
  labels:
    name: volume01
spec:
  storageClassName: my-localstorageclass
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data