apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: volumeclaim01
      containers:
      - name: myapp
        image: busybox
        command: ["sleep"]
        args: ["600"]
        volumeMounts:
        - mountPath: "/data"
          name: myvolume
s
